### ISSUE TITLE
Class 'GameType' not found

### ISSUE THREAD

**Issue by Nano-GG** [sct/League#2]
Hello,

First of all i want to say thank you very much for this project, i hope you can finish soon. amazing work, looks very promising!

Now, i'm trying to test but i'm having this problem:

``` php
<?php

require 'vendor/autoload.php';

use sct\League\Summoner;
//use sct\League\Common\GameType;

$dyrus = new Summoner("Dyrus", "na", "123456-789-10-11-asdf");

$dyrus->getSummonerLevel();
$dyrus->getStats();
$dyrus->getRankedStats();
$dyrus->getStatsForGameType(GameType::Unranked);
```

`Fatal error: Class 'GameType' not found in H:\xampp\htdocs\index.php on line 12`

but if i put "use sct\League\Common\GameType;" just below "use sct\League\Summoner;"

``` php
<?php

require 'vendor/autoload.php';

use sct\League\Summoner;
use sct\League\Common\GameType;

$dyrus = new Summoner("Dyrus", "na", "123456-789-10-11-asdf");

$dyrus->getSummonerLevel();
$dyrus->getStats();
$dyrus->getRankedStats();
$dyrus->getStatsForGameType(GameType::Unranked);
$dyrus->getStatsForChampionByName("Darius");
```

 the problem is now:

`Notice: Undefined index: aggregatedStats in H:\xampp\htdocs\src\sct\League\Common\GameType.php on line 142
Warning: Invalid argument supplied for foreach() in H:\xampp\htdocs\src\sct\League\Common\GameType.php on line 142`

i believe is my fault but i cannot see where is the problem.

thanks for your time.

**Comment by sct** [comment]
What?

**Comment by Nano-GG** [comment]
@sct fixed post, sorry.

**Comment by sct** [comment]
Interesting. The only way I see this happening is if for whatever reason some queues arent returning any aggregated stats. Let me try to reproduce it. Give me a bit.

**Comment by sct** [comment]
Should be fine now

**Comment by Nano-GG** [comment]
@sct thank you very much.. any idea why doesnt work if i dont put "use sct\League\Common\GameType;" on index.php

**Comment by sct** [comment]
If you are using the GameType constants you have to well, be using GameType.

See Here:

```
$dyrus->getStatsForGameType(GameType::Unranked);
```

Using GameType::Unranked requires the GameType class. You can swap out that out for just "Unranked" if you don't feel like using constants :)

**Comment by Nano-GG** [comment]
the strange is "use sct\League\Common\GameType;" are declared on Summoner, why i have to re-declare on index.php?

btw, with "Unranked" is working perfect!

**Comment by sct** [comment]
It being declared on Summoner does not mean you have access to it wherever Summoner is used. It just means Summoner itself is using it.

I would look in GameType.php for all the values you can pass directly into the stats request without using the GameType constants.
