### ISSUE TITLE
Riot API Updated

### ISSUE THREAD

**Issue by Nano-GG** [sct/League#3]
Hello,

Just to note that riot recently updated his API.

http://developer.riotgames.com/discussion/riot-games-api/show/rXIx7RPr

Thanks for your work.

**Comment by Michalosu** [comment]
Undefined index: timestamp [../sct/League/League/League.php, line 54]
In Debugger I see "timestamp => null". In new version API field "timestamp" doesn't exist.

**Comment by sct** [comment]
Yep thanks for the heads up. I will get everything updated for 1.2 and 2.2 this weekend.

**Comment by sct** [comment]
@Michalosu It seems the documentation says timestamp should still exist but it doesn't which is probably a mistake on Riots part. No big deal. Pushed a fix.
